CREATE DATABASE ride_register_db;
GO

USE ride_register_db;
GO


CREATE TABLE Members (
MemberID INT IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
DateOfBirth DATE NOT NULL,
PhoneNumber VARCHAR(11),
Address VARCHAR(100) NOT NULL
);

CREATE TABLE Memberships (
MembershipID INT IDENTITY(1,1) PRIMARY KEY,
Role VARCHAR(50) NOT NULL,
StartDate DATE NOT NULL,
ExpiryDate DATE NOT NULL,
Status VARCHAR(50) NOT NULL,
MemberID INT NOT NULL

FOREIGN KEY(MemberID) REFERENCES Members(MemberID)
ON DELETE CASCADE

);

CREATE TABLE dbo.Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL, 
    MemberID INT NULL,

    CONSTRAINT FK_Users_Members
        FOREIGN KEY (MemberID)
        REFERENCES dbo.Members(MemberID)
        ON DELETE SET NULL
);

CREATE TABLE Route(
RouteID INT IDENTITY(1,1) PRIMARY KEY,
RouteName VARCHAR(50) NOT NULL,
StartPoint VARCHAR(100) NOT NULL,
EndPoint VARCHAR(100) NOT NULL,
Fare DECIMAL (4,2) NOT NULL
);

CREATE TABLE Tricycle (
TricycleID INT IDENTITY(1,1) PRIMARY KEY,
OwnerMemberID INT NOT NULL,
DriverMemberID INT NULL,
RouteID INT NOT NULL,
PlateNumber VARCHAR(20) NOT NULL UNIQUE,
Model VARCHAR(50) NOT NULL,

FOREIGN KEY (OwnerMemberID) REFERENCES Members(MemberID) ON DELETE NO ACTION,
FOREIGN KEY (DriverMemberID) REFERENCES Members(MemberID) ON DELETE NO ACTION,
FOREIGN KEY (RouteID) REFERENCES Route(RouteID) ON DELETE NO ACTION
);